apiVersion: v1
kind: ConfigMap
metadata:
  name: algorithm-config
  namespace: algorithm-test
data:
  config.json: |
    {
      "algorithms": {
        "fuzzy": {
          "enabled": true,
          "criteria_weights": {
            "response_time": 0.3,
            "cpu_usage": 0.2,
            "memory_usage": 0.15,
            "availability": 0.25,
            "error_rate": 0.1
          }
        },
        "stochastic": {
          "enabled": true,
          "exploration_rate": 0.1,
          "sample_size": 50
        },
        "adaptive": {
          "enabled": true,
          "context_weights": {
            "user_locality": 0.3,
            "request_type": 0.25,
            "time_of_day": 0.15,
            "load_balancing": 0.2,
            "session_affinity": 0.1
          }
        }
      },
      "service_mesh": {
        "type": "istio",
        "monitoring": {
          "prometheus": true,
          "jaeger": true,
          "grafana": true
        }
      }
    }
