apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-ambient-config
  namespace: istio-system
data:
  mesh: |
    defaultConfig:
      proxyStatsMatcher:
        inclusionRegexps:
        - ".*outlier_detection.*"
        - ".*circuit_breakers.*"
        - ".*upstream_rq_retry.*"
        - ".*_cx_.*"
      holdApplicationUntilProxyStarts: true
    extensionProviders:
    - name: prometheus
      prometheus:
        configOverride:
          metric_relabeling_configs:
          - source_labels: [__name__]
            regex: 'istio_.*'
            target_label: __name__
            replacement: '${1}'
    defaultProviders:
      metrics:
      - prometheus
