apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: algorithm-test-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: algorithm-test-role
subjects:
  - kind: ServiceAccount
    name: algorithm-test-sa
    namespace: algorithm-test
